### ISSUE TITLE
安卓设备是否必须root才能使用？

### ISSUE THREAD

**Issue by SaiCateDoan** [AXiX-official/CrossCore-Internationalizer#2]
我再三确认了readme中没有root相关的内容，所以直接上真机
使用手机浏览器访问ilist.txt正常，但是APP访问始终卡在TLS handshake failed
搜索mitmproxy相关的教程之后得知在安卓7.0以上需要将证书安装为系统证书，这是必须root才能实现的
我无法确定教程的真伪，因此发在了issue，如果确认了这个问题，希望更新到readme中，避免无谓的尝试

PS：高版本模拟器可能需要设置修改系统盘可写之后才能正常使用

**Comment by AXiX-official** [comment]
我自己的设备是Android 12非root环境可以运行。当然我会在readme中补充相关内容
