### ISSUE TITLE
iOS+Surge失败

### ISSUE THREAD

**Issue by AnonymousNone** [AXiX-official/CrossCore-Internationalizer#3]
Surge操作流程：右上角配置，文本模式编辑，写入提供的配置；捕获-MitM-配置-安装证书-信任证书

游戏文件操作流程：分别测试了1. international和close都不改。2. 只把international改1，close不做改动。3. international改为1并删除close

以上流程后重启游戏均未触发资源下载

**Comment by AXiX-official** [comment]
Surge方法是由@lolita-id 贡献的，我没有实际操作过也不清楚技术细节。他本人是成功操作了的。你可以先使用文件替换的方法。记得更新仓库，刚刚修复了一处脚本中的错误。

**Comment by AnonymousNone** [comment]
解决了，缺少了一步打开rewrite的操作，需要在surge主界面-修改-rewrite，打开就可以
international需要改为1，配置和MitM操作流程不变

**Comment by lolita-id** [comment]
> 解决了，缺少了一步打开rewrite的操作，需要在surge主界面-修改-rewrite，打开就可以 international需要改为1，配置和MitM操作流程不变

抱歉是我疏忽忘记提到，已经在 #5 里更新详细说明。
