### ISSUE TITLE
高版本（7以上）安卓是否必须root才能成功？

### ISSUE THREAD

**Issue by AmahaSuzune** [AXiX-official/CrossCore-Internationalizer#8]
全部按照步骤执行以后卡在Client TLS handshake failed . The client may not trust the proxy's certificate for cdn.megagamelog.com
查阅了一些相关资料以后发现Android 7以上版本APP不信任用户证书，只信任系统证书
而自定义的系统证书需要root，非root机似乎此方法不可行
本人设备为港版三星S22U，系统为Android 13

**Comment by Caimankekw** [comment]
S23U国际版+安卓14相同错误，使用--set tls_version_client_min=SSL3在terminal中启动mitmproxy也无法解决该问题。
![Screenshot_20240211_204521_Settings](https://github.com/AXiX-official/CrossCore-Internationalizer/assets/115722728/15743593-ae06-4263-a898-63157f713172)

**Comment by Caimankekw** [comment]
> S23U国际版+安卓14相同错误，使用--set tls_version_client_min=SSL3在terminal中启动mitmproxy也无法解决该问题。 ![Screenshot_20240211_204521_Settings](https://private-user-images.githubusercontent.com/115722728/303947358-15743593-ae06-4263-a898-63157f713172.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2ODk2NzAsIm5iZiI6MTcwNzY4OTM3MCwicGF0aCI6Ii8xMTU3MjI3MjgvMzAzOTQ3MzU4LTE1NzQzNTkzLWFlMDYtNDI2My1hODk4LTYzMTU3ZjcxMzE3Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMVQyMjA5MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MTg0NzQwM2EzYTUzOTUzM2E2Yzc5YjBhMjYyOWExN2IxMjVjZTNhOWM4YmRlMDNlZTY1ZmZiZDVkZGFhYzE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.N-U86brOx9SSQ8sy96kdY4fjudDHOuUOSHhtBZEzeFs)
安卓13或以上似乎没有办法在无root的情况下将system文件夹从read-only修改为read-write，即使通过数据线链接电脑用adb mount命令也会显示不支持该文件夹属性的修改。因此将cer文件通过openssl转写成.0文件放入系统证书文件夹内不可行。

**Comment by AXiX-official** [comment]
请先查阅已经close的issue。
